#!/bin/sh
set -eu
root=$(mktemp -d); results="$root/results.jsonl"; pass=0; fail=0
run_case() {
  name=$1; task=$2; project="$root/$name/project"; state="$root/$name/state"; mkdir -p "$project" "$state" "$state/backups"; provider=opencode; test "$task" = secret && provider=openrouter || true; printf '{"version":1,"provider":"%s","openRouterBaseUrl":"https://example.invalid","model":"big-pickle","createdAt":"now","updatedAt":"now"}\n' "$provider" > "$state/config.json"
  key_env=""; test "$task" = secret && key_env="OPENROUTER_API_KEY=fixture-secret-value" || true
  if env AGENTCTL_HOME="$state" AGENTCTL_SCENARIO_PROJECT="$project" AGENTCTL_SCENARIO_TASK="$task" $key_env node dist/cli.js run "$name" >"$root/$name.out" 2>&1; then status=0; else status=$?; fi
  ok=0; assertions='[]'; case "$task" in install) if test -x "$project/bin/claude" && test -x "$project/bin/codex" && test -x "$project/bin/hermes"; then ok=1; assertions='["three agent binaries"]'; fi;; version) if grep -q Codex "$root/$name.out"; then ok=1; assertions='["version output"]'; fi;; switch) if grep -q big-pickle "$project/config.json"; then ok=1; assertions='["model persisted"]'; fi;; endpoint) if grep -q opencode.ai "$project/provider.json"; then ok=1; assertions='["endpoint persisted"]'; fi;; edit|merge) if grep -q unrelated "$project/config.json"; then ok=1; assertions='["unrelated config preserved"]'; fi;; repair) if grep -q repaired "$project/runtime.json"; then ok=1; assertions='["runtime repaired"]'; fi;; bad-path|broken-json|invalid-model|download|package|network-failure|permission-failure) if grep -q diagnostic "$root/$name.out"; then ok=1; assertions='["diagnostic and next step"]'; fi;; interrupt) if test "$status" -eq 130; then ok=1; assertions='["interrupt exit"]'; fi;; continue) if test -f "$project/continued"; then ok=1; assertions='["continued marker"]'; fi;; restore) if grep -q restored "$root/$name.out"; then ok=1; assertions='["restore report"]'; fi;; uninstall) if grep -q residual "$root/$name.out"; then ok=1; assertions='["residual report"]'; fi;; secret) if test "$(grep -c '<redacted>' "$root/$name.out")" -gt 0 && ! grep -q fixture-secret-value "$root/$name.out" && ! grep -R -q fixture-secret-value "$state"; then ok=1; assertions='["redacted output","secret absent from state"]'; fi;; *) if test "$status" -eq 0; then ok=1; assertions='["exit zero"]'; fi;; esac
  if test "$ok" -eq 1; then pass=$((pass+1)); result=pass; else fail=$((fail+1)); result=fail; fi
  printf '{"case":"%s","result":"%s","assertions":%s}\n' "$name" "$result" "$assertions" | tee -a "$results"
}
export AGENTCTL_PI_CLI="$PWD/scripts/fake-pi.sh"
run_case install install; run_case version version; run_case switch switch; run_case endpoint endpoint; run_case edit edit; run_case merge merge; run_case repair repair; run_case bad-path bad-path; run_case broken-json broken-json; run_case invalid-model invalid-model; run_case network network-failure; run_case permission permission-failure; run_case download download; run_case package package; run_case interrupted interrupt; run_case continued continue; run_case restore restore; run_case uninstall uninstall; run_case secret secret; run_case generic generic
printf '{"summary":{"passed":%s,"failed":%s,"total":%s}}\n' "$pass" "$fail" $((pass+fail)); test "$fail" -eq 0
